version: '3.9'
services:
  #Nginx Service
  server:
    restart: unless-stopped
    image: nginx
    depends_on:
      - app
    volumes:
      - ./:/usr/share/nginx/html/

    command: [ nginx-debug, '-g', 'daemon off;' ]
    container_name: server
    ports:
      - "81:80"
  #javascript Service
  app:
    image: node:slim
    container_name: solitaire
    restart: unless-stopped
    tty: true
    working_dir: /usr/share/nginx/html/
    volumes:
      - ./:/usr/share/nginx/html/